server:
  port: 8761

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: eureka-server
  server:
    renewal-percent-threshold: 0.90